name: Test

on: [push, pull_request]

jobs:

  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8

    - name: Install Dependencies
      run: pip install .[lint]

    - name: Run Black
      run: black --check --force-exclude=vyper/version.py ./vyper ./tests ./setup.py

    - name: Run flake8
      run: flake8 ./vyper ./tests ./setup.py
      if: always()

    - name: Run isort
      run: isort --check-only --diff ./vyper ./tests ./setup.py
      if: always()

  docs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Install Tox
        run: pip install tox

      - name: Run Tox
        run: TOXENV=docs tox -r

  mypy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8

    - name: Install Tox
      run: pip install tox

    - name: Run Tox
      run: TOXENV=mypy tox -r

  py37-core:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7

    - name: Install Tox
      run: pip install tox

    - name: Run Tox
      run: TOXENV=py37-core tox -r

    - name: Upload Coverage
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./coverage.xml

  py37-no-opt:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7

    - name: Install Tox
      run: pip install tox

    - name: Run Tox
      run: TOXENV=py37-no-opt tox -r


  py38-core:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8

    - name: Install Tox
      run: pip install tox

    - name: Run Tox
      run: TOXENV=py38-core tox -r

    - name: Upload Coverage
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./coverage.xml

  py38-no-opt:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8

    - name: Install Tox
      run: pip install tox

    - name: Run Tox
      run: TOXENV=py38-no-opt tox -r


  py39-core:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Set up Python 3.9
      uses: actions/setup-python@v1
      with:
        python-version: 3.9

    - name: Install Tox
      run: pip install tox

    - name: Run Tox
      run: TOXENV=py39-core tox -r

    - name: Upload Coverage
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./coverage.xml

  py39-no-opt:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Set up Python 3.9
      uses: actions/setup-python@v1
      with:
        python-version: 3.9

    - name: Install Tox
      run: pip install tox

    - name: Run Tox
      run: TOXENV=py39-no-opt tox -r


  fuzzing:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8

    - name: Install Tox
      run: pip install tox

    - name: Run Tox
      run: TOXENV=fuzzing tox -r

    - name: Upload Coverage
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./coverage.xml

  memory:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8

    - name: Install Tox
      run: pip install tox

    - name: Run Tox
      run: TOXENV=memory tox -r

    - name: Upload Coverage
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./coverage.xml
